### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/sos-r#5]
```
$ python test_R_kernel.py
/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/manager.py:72: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_name_changed(self, name, old, new):
EEEE
======================================================================
ERROR: testGetPythonDataFrameFromR (__main__.TestRKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_R_kernel.py", line 61, in testGetPythonDataFrameFromR
    ''')
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/ipykernel/tests/utils.py", line 66, in execute
    reply = kc.get_shell_msg(timeout=TIMEOUT)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

======================================================================
ERROR: testGetPythonDataFromR (__main__.TestRKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_R_kernel.py", line 96, in testGetPythonDataFromR
    ''')
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/ipykernel/tests/utils.py", line 66, in execute
    reply = kc.get_shell_msg(timeout=TIMEOUT)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

======================================================================
ERROR: testPutRDataFrameToPython (__main__.TestRKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_R_kernel.py", line 131, in testPutRDataFrameToPython
    execute(kc=kc, code='%use R')
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/ipykernel/tests/utils.py", line 66, in execute
    reply = kc.get_shell_msg(timeout=TIMEOUT)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

======================================================================
ERROR: testPutRDataToPython (__main__.TestRKernel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_R_kernel.py", line 165, in testPutRDataToPython
    """)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/ipykernel/tests/utils.py", line 66, in execute
    reply = kc.get_shell_msg(timeout=TIMEOUT)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "/Users/manchongleong/anaconda/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

----------------------------------------------------------------------
Ran 4 tests in 70.932s

FAILED (errors=4)
```

**Comment by BoPeng** [comment]
Sorry, the tests fail due to changes in `sos-notebook` and I did not update them. Please update to the newest released version of `sos-notebook`, merge the master branch of `sos-r` to your branch and try again.

**Comment by BoPeng** [comment]
AppVoyer tests passed but the processed hang there for an hour, leading to failed status. This only happens on windows so I will have to try to reproduce it there.

**Comment by HenryLeongStat** [comment]
>Sorry, the tests fail due to changes in sos-notebook and I did not update them. Please update to the newest released version of sos-notebook, merge the master branch of sos-r to your branch and try again.

Still fail after I update `sos-notebook` to 0.9.13.6 and merge the master branch of `sos-r` to my local branch.

```
$ ls | grep sos
sos
sos-0.9.13.3.dist-info
sos_bash
sos_bash-0.9.12.1.dist-info
sos_bash-0.9.12.2-py3.6.egg
sos_bioinfo
sos_bioinfo-0.9.10.1.dist-info
sos_javascript
sos_javascript-0.9.12.1.dist-info
sos_javascript-0.9.12.2-py3.6.egg
sos_julia
sos_julia-0.9.12.0.dist-info
sos_julia-0.9.12.1-py3.6.egg
sos_matlab
sos_matlab-0.9.12.0.dist-info
sos_matlab-0.9.12.1-py3.6.egg
sos_notebook
sos_notebook-0.9.13.2.dist-info
sos_notebook-0.9.13.6-py3.6.egg
sos_pbs
sos_pbs-0.9.10.4.dist-info
sos_python
sos_python-0.9.12.0.dist-info
sos_python-0.9.12.1-py3.6.egg
sos_r-0.9.12.1-py3.6.egg
sos_rq-0.9.10.2-py3.6.egg
sos_sas
sos_sas-0.9.12.1.dist-info
sos_sas-0.9.12.2-py3.6.egg
```

**Comment by BoPeng** [comment]
Remove everything, run `pip install sos sos-notebook -U`, then remove `sos-r` directories under `site-packages` before running `python setup.py install` from your own branch.

**Comment by HenryLeongStat** [comment]
Fixed! But the kernel still needs some works...
